name: publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  create-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create service account key & env file
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          SECRETS_ENVIRONMENT: ${{ secrets.SECRETS_ENVIRONMENT }}
        run: |
          echo "$GCP_SA_KEY" > maxpollo.json
          echo "$SECRETS_ENVIRONMENT" > .env

  deploy:
    needs: create-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Obligatorio: tu User Token
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Obligatorio: tu Org/Team ID
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Obligatorio: tu Project ID
          vercel-args: "--prod" # Pasa flags al CLI (aquí, despliegue en prod)
          github-token: ${{ secrets.GITHUB_TOKEN }} # Opcional: para comentar en PRs

