name: publish

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      # 1. Clon치s tu repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Prepar치s QEMU para builds multiplataforma (opcional)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3. Instal치s Buildx para Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Login al GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CD }}

      # 5. Build y push de la imagen Docker
      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/Jhoiner243/implements-back:latest
          docker push ghcr.io/Jhoiner243/implements-back:latest

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:
      # 6. Instal치s Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 7. Deploy a Firebase Hosting
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"
